// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calc_est
double calc_est(NumericMatrix X, IntegerVector H);
RcppExport SEXP _MuniCandS_calc_est(SEXP XSEXP, SEXP HSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type H(HSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_est(X, H));
    return rcpp_result_gen;
END_RCPP
}
// calc_est_arma
double calc_est_arma(const arma::mat& X, const arma::uvec& H);
RcppExport SEXP _MuniCandS_calc_est_arma(SEXP XSEXP, SEXP HSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type H(HSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_est_arma(X, H));
    return rcpp_result_gen;
END_RCPP
}
// S2Cpi
NumericVector S2Cpi(NumericVector x);
RcppExport SEXP _MuniCandS_S2Cpi(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(S2Cpi(x));
    return rcpp_result_gen;
END_RCPP
}
// intlin
double intlin(double x, NumericVector X, NumericVector Y);
RcppExport SEXP _MuniCandS_intlin(SEXP xSEXP, SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(intlin(x, X, Y));
    return rcpp_result_gen;
END_RCPP
}
// ajus
double ajus(double y, NumericVector Y);
RcppExport SEXP _MuniCandS_ajus(SEXP ySEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(ajus(y, Y));
    return rcpp_result_gen;
END_RCPP
}
// Cpi2C
NumericVector Cpi2C(NumericVector phi);
RcppExport SEXP _MuniCandS_Cpi2C(SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(Cpi2C(phi));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MuniCandS_calc_est", (DL_FUNC) &_MuniCandS_calc_est, 2},
    {"_MuniCandS_calc_est_arma", (DL_FUNC) &_MuniCandS_calc_est_arma, 2},
    {"_MuniCandS_S2Cpi", (DL_FUNC) &_MuniCandS_S2Cpi, 1},
    {"_MuniCandS_intlin", (DL_FUNC) &_MuniCandS_intlin, 3},
    {"_MuniCandS_ajus", (DL_FUNC) &_MuniCandS_ajus, 2},
    {"_MuniCandS_Cpi2C", (DL_FUNC) &_MuniCandS_Cpi2C, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_MuniCandS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
