# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_est <- function(X, H) {
    .Call(`_MuniCandS_calc_est`, X, H)
}

calc_est_arma <- function(X, H) {
    .Call(`_MuniCandS_calc_est_arma`, X, H)
}

S2Cpi <- function(x) {
    .Call(`_MuniCandS_S2Cpi`, x)
}

intlin <- function(x, X, Y) {
    .Call(`_MuniCandS_intlin`, x, X, Y)
}

ajus <- function(y, Y) {
    .Call(`_MuniCandS_ajus`, y, Y)
}

Cpi2C <- function(phi) {
    .Call(`_MuniCandS_Cpi2C`, phi)
}

